export enum CaseType {
  CROWN = 'CROWN',
  BRIDGE = 'BRIDGE',
  IMPLANT = 'IMPLANT',
  VENEER = 'VENEER',
  CUSTOM_ABITMENT = 'CUSTOM_ABITMENT',
  IBAR = 'IBAR',
  MOCKUP_DSD = 'MOCKUP+DSD',
  FRAMEWORK = 'FRAMEWORK',
  SURGICAL_GUID_DESIGN = 'SURGICAL_GUID_DESIGN',
}
